/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisvelasco' at '13/12/16 10:16' with Gradle 3.0
 *
 * @author luisvelasco, @date 13/12/16 10:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
