/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xavi' at '31/01/17 8:39' with Gradle 2.14.1
 *
 * @author xavi, @date 31/01/17 8:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
