/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '29/11/16 9:48' with Gradle 2.13
 *
 * @author mati, @date 29/11/16 9:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
