
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class Articulo
	{
		public virtual void Build ()
		{
			// Action group PArticulo.Articulo
		}
	}
}
