
// This file has been generated by the GUI designer. Do not modify.
namespace Org.InstitutoSerpis.Ad
{
	public partial class ComboboxHelper
	{
		public virtual void Build ()
		{
			// Action group Org.InstitutoSerpis.Ad.ComboboxHelper
		}
	}
}
