/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xavi' at '17/01/17 8:26' with Gradle 2.14.1
 *
 * @author xavi, @date 17/01/17 8:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
